version: "3.9"

services:
  careflow-backend:
    image: careflow-backend:latest
    container_name: careflow-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Host port 8080 -> Container port 8080
    env_file:
      - .env
    volumes:
      - ./src/main/java:/app/src/main/java
      - ./src/main/resources:/app/src/main/resources
      - ./src/main/resources/certs:/app/certs
